version: "3"
services:
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: covid-19-status
    restart: unless-stopped
    image: covid-19-status
    ports:
      - "9063:9063"
    network_mode: bridge 